name: Publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Release
    strategy:
      matrix:
        kind: ['windows']
        include:
          - kind: windows
            os: windows-latest
            target: win-x64
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Build
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name="Bulk-vCard-QR-Generator-$tag-${{ matrix.target }}"

          # Build everything
          dotnet publish Bulk-vCard-QR-Generator/Bulk-vCard-QR-Generator.csproj --framework net6.0-windows --runtime "${{ matrix.target }}" -c Release -o "$release_name"

          # Pack files
          if [ "${{ matrix.target }}" == "win-x64" ]; then
            # Pack to zip for Windows
            7z a -tzip "${release_name}.zip" "./${release_name}/Bulk-vCard-QR-Generator.exe" "README.md" "Example.xlsx"
          else
           tar czvf "${release_name}.tar.gz" "$release_name"
          fi

          # Delete output directory
          rm -r "$release_name"

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "Bulk-vCard-QR-Generator-v*"
          
